name: partage_data
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_1
  - anyio=4.6.0=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h66e93f0_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - biopython=1.85=py312h66e93f0_1
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312h68727a3_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.6=py312h2ec8cdc_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - flatbuffers=24.3.25=h59595ed_0
  - fonttools=4.54.1=py312h66e93f0_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_1
  - gast=0.6.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - grpcio=1.65.5=py312h374181b_0
  - gseapy=1.1.4=py312h004ce86_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py312hd203070_103
  - hdbscan=0.8.39=py312hc0a28a1_0
  - hdf5=1.14.4=nompi_h2d575fe_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.6=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperopt=0.2.7=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.28.0=pyh707e725_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h7900ff3_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - keras=3.7.0=pyh753f3f9_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_2
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=24_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=24_linux64_openblas
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libgrpc=1.65.5=hf5c653b_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=24_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.44=hadc24fc_0
  - libprotobuf=5.27.5=h5b01275_2
  - libre2-11=2024.07.02=hbbce691_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.7.0=he137b08_1
  - libtorch=2.4.1=cpu_generic_hca457ed_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py312h374181b_1
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=2.1.5=py312h66e93f0_1
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.0.2=pyhd8ed1ab_0
  - ml_dtypes=0.4.0=py312hf9745cd_2
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.0.7=py_1
  - namex=0.0.8=pyhd8ed1ab_1
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.4.2=pyh267e887_2
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.60.0=py312h83e6fd3_0
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.5.2=h26f9b46_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.13.1=py312h68727a3_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.1=py312hfb8ada1_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pgmpy=1.0.0=py312h7900ff3_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h56024de_1
  - pip=24.2=pyh8b19718_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - protobuf=5.27.5=py312h2ec8cdc_0
  - psutil=6.0.0=py312h66e93f0_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py4j=0.10.9.8=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhff2d567_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.9.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.7=hc5c86c4_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyhe33e51e_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytorch=2.4.1=cpu_generic_py312h916ba9d_2
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h66e93f0_1
  - pyzmq=26.2.0=py312hbf22597_2
  - qhull=2020.2=h434a139_5
  - qnorm=0.9.0=pyhff2d567_0
  - re2=2024.07.02=h77b4e00_1
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.20.0=py312h12e396e_1
  - scikit-learn=1.5.2=py312h7a48858_1
  - scipy=1.14.1=py312h7d485d2_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.8=h1b44611_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py312hc0a28a1_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.0.0=hceb3a55_0
  - tensorboard=2.17.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py312hda17c39_2
  - tensorflow=2.17.0=cpu_py312h69ecde4_3
  - tensorflow-base=2.17.0=cpu_py312h4c54302_3
  - tensorflow-estimator=2.17.0=cpu_py312h4f468f2_3
  - termcolor=2.5.0=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py312h66e93f0_1
  - tqdm=4.67.0=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024b=hc8b5060_0
  - umap-learn=0.5.7=py312h7900ff3_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - appdirs==1.4.4
    - astroid==2.15.8
    - datacache==1.4.1
    - demultiplexer==1.2.1
    - dill==0.3.9
    - et-xmlfile==2.0.0
    - fasttreeshap==0.1.6
    - gnureadline==8.2.13
    - gtfparse==2.5.0
    - hyperas==0.4.1
    - isort==5.13.2
    - keras-tuner==1.4.7
    - kt-legacy==1.0.5
    - lazy-object-proxy==1.10.0
    - mccabe==0.7.0
    - memoized-property==1.0.3
    - mock==5.1.0
    - nvidia-nccl-cu12==2.23.4
    - openpyxl==3.1.5
    - polars==0.20.31
    - progressbar33==2.4
    - pyarrow==14.0.2
    - pyensembl==2.3.13
    - pyideogram==0.1.0
    - pylint==2.17.7
    - pysam==0.23.3
    - pysimplegui==5.0.8.3
    - serializable==0.4.1
    - shap==0.45.0
    - simplejson==3.19.3
    - slicer==0.0.7
    - tinytimer==0.0.0
    - tomlkit==0.13.2
    - typechecks==0.1.0
    - wrapt==1.16.0
    - xgboost==2.1.3
    - xlsxwriter==3.2.9
prefix: /users/9/dicki214/.conda/envs/pandas
