name: snakemake
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alabaster=1.0.0=pyhd8ed1ab_1
  - amply=0.1.6=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bedtools=2.31.1=hf5e1c6e_2
  - biopython=1.85=py312h66e93f0_1
  - bowtie2=2.5.4=he96a11b_5
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bwa=0.7.18=he4a0461_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.9=h1d3f3f2_0
  - coin-or-clp=1.17.10=h07f2a63_0
  - coin-or-osi=0.108.11=h6514dde_1
  - coin-or-utils=2.11.12=h99da652_1
  - coincbc=2.10.12=1_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.0=py312h68727a3_2
  - cutadapt=4.9=py312hf67a6ed_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - datrie=0.8.2=py312h66e93f0_8
  - deeptools=3.5.6=pyhdfd78af_0
  - deeptoolsintervals=0.1.9=py312ha9c1134_11
  - dnaio=1.2.2=py312hf67a6ed_0
  - docutils=0.21.2=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonttools=4.54.1=py312h178313f_1
  - freetype=2.12.1=h267a509_2
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - htslib=1.21=h5efdd21_0
  - humanfriendly=10.0=pyhd8ed1ab_6
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - immutables=0.21=py312h66e93f0_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - isa-l=2.31.0=h4bc722e_2
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=25_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=8.14.0=h332b0f4_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - liblapacke=3.9.0=25_linux64_openblas
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libopenssl-static=3.5.0=hb9d3cd8_1
  - libpng=1.6.47=h943b412_0
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=h6565414_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - logmuse=0.2.8=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h178313f_0
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - mdurl=0.1.2=pyhd8ed1ab_0
  - munkres=1.0.7=py_1
  - mysql-connector-c=6.1.11=h659d440_1008
  - narwhals=1.41.0=pyhe01879c_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - numpy=2.2.6=py312h72c5963_0
  - numpydoc=1.8.0=pyhd8ed1ab_1
  - openjdk=8.0.412=h2b85faf_2
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.5.0=h7b32b05_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pbzip2=1.1.13=h1fcc475_2
  - pephubclient=0.4.4=pyhd8ed1ab_0
  - peppy=0.40.7=pyhd8ed1ab_1
  - perl=5.32.1=7_hd590300_perl5
  - pigz=2.8=h2797004_0
  - pillow=11.0.0=py312h7b63e92_0
  - pip=24.2=pyh8b19718_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.3=pyhd8ed1ab_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - plotly=6.1.2=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - psutil=6.0.0=py312h66e93f0_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulp=2.8.0=py312h7900ff3_0
  - py2bit=0.3.3=py312h0fa9677_1
  - pybigwig=0.3.24=py312h0e9d276_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.8.2=py312h06a4308_0
  - pydantic-core=2.20.1=py312hb02cf49_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pysam=0.22.1=py312hcfdcdd7_2
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.3=pyhd8ed1ab_0
  - python=3.12.7=hc5c86c4_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-isal=1.7.1=py312h66e93f0_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python-zlib-ng=0.5.1=py312h27ca174_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h66e93f0_1
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.9.3=pyhd8ed1ab_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rpds-py=0.20.0=py312h12e396e_1
  - samtools=1.21=h50ea8bc_0
  - scikit-learn=1.6.1=py312h7a48858_0
  - scipy=1.14.1=py312h62794b6_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slack-sdk=3.33.1=pyha770c72_0
  - slack_sdk=3.33.1=hd8ed1ab_0
  - smart_open=7.0.5=pyhd8ed1ab_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=8.24.1=hdfd78af_0
  - snakemake-interface-common=1.17.4=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.2=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.1.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=3.3.0=pyhdfd78af_0
  - snakemake-minimal=8.24.1=pyhdfd78af_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - statsmodels=0.14.4=py312hc0a28a1_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.2=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typer=0.12.5=pyhd8ed1ab_0
  - typer-slim=0.12.5=pyhd8ed1ab_0
  - typer-slim-standard=0.12.5=hd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - ucsc-bigwigtowig=469=h664eb37_1
  - ucsc-wigtobigwig=482=hdc0a859_0
  - unicodedata2=15.1.0=py312h66e93f0_1
  - urllib3=2.2.3=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py312h66e93f0_1
  - xopen=2.0.2=pyh707e725_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - yte=1.5.4=pyha770c72_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.2=h5888daf_0
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /users/9/dicki214/.conda/envs/snakemake
